### ISSUE TITLE
Wires going everywhere

### ISSUE THREAD

**Issue by Ekdohibs** [Jeija/minetest-mod-mesecons#128]
![screenshot - 01042014 - 04 22 53 am](https://f.cloud.github.com/assets/1733537/1844406/7694f7e0-7526-11e3-8e42-17bf085ccac5.png)

![screenshot - 01042014 - 04 23 04 am](https://f.cloud.github.com/assets/1733537/1844423/053e2fb6-7527-11e3-98d7-879e425b387c.png)

Repository link for the above:  https://github.com/Novatux/wires

This code allows wires going in every possible direction, along walls, etc.
However, it has a major drawback: it requires 331 nodes per wire (so that makes 331 for off wires, and 331 for on ones)

Therefore, I need thoughts on it.

**Comment by Jeija** [comment]
I think the developer resources are missing to implement this. Great code though, but not realistic to be maintained well at the current state of mesecons.
