### ISSUE TITLE
invalid node position data in mesecon:register_on_mvps_move() 

### ISSUE THREAD

**Issue by VanessaE** [Jeija/minetest-mod-mesecons#147]
(sad thing is, I committed this function to mesecons but I dunno how to fix it :P)

It appears that the register_on_mvps_move() function is not always returning a list of positions - sometimes it returns a list of actual nodes.  For example, in this code segment from the item transport code in Pipeworks (with print() calls added for debugging when this crash came up):

```lua
if minetest.get_modpath("mesecons_mvps") ~= nil then
	mesecon:register_mvps_unmov("pipeworks:tubed_item")
	mesecon:register_on_mvps_move(function(moved_nodes)
		local objects_to_move = {}
		for _, n in ipairs(moved_nodes) do
			print("---------")
			print(dump(n.oldpos))
			local objects = minetest.get_objects_inside_radius(n.oldpos, 1)
```

The example given to me to reproduce the problem (and indeed, this works quite reliably) is: put two glass blocks, a movestone, and two more glass blocks side by side, like so:  [glass] [glass] [movestone] [glass] [glass]

Attach a wall button to the movestone and click it to cause it to push some of the glass.  The above code will print this:

```---------
{["y"] = 9, ["x"] = -432, ["z"] = 267}
---------
{["y"] = 9, ["x"] = -431, ["z"] = 267}
---------
{["param1"] = 95, ["name"] = "default:glass", ["param2"] = 0}
```

This can't possibly be right. :-)  As you can guess, this sort of output causes that get_objects_inside_radius() call in the above code snippet to crash. Seems like it might be an off-by-one error, as there are three entries in the list but there were only two glass being pushed in the example.

**Comment by Jeija** [comment]
I assume this bug doesn't exist anymore since movestones and pistons had a large overhaul recently. In case it is still reproducible, feel free to re-open this issue.
