### ISSUE TITLE
Meshes branch

### ISSUE THREAD

**Issue by VanessaE** [Jeija/minetest-mod-mesecons#192]
I've started a new branch on this repository to receive mesh-node updates as needed:

https://github.com/Jeija/minetest-mod-mesecons/tree/meshes

My first contribution is for the water turbine, as previously mentioned.  It's a drop-in replacement for the old nodebox model - simply merge and it will work as-is (provided Minetest engine is up-to-date enough of course).

The model uses a single 48x48 pixel UV-mapped texture for each of its "on" and "off" states.  The turbine blades do not rotate when the unit is "on" (Minetest does not support animations in mesh node models yet).  That'll come later.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/1733537/5160603/9b01ac68-735e-11e4-97bf-b9a9acf73a9d.png)

Second, the wall lever.  36x36 px UV-mapped texture for each of on/off states, and the model/node goes right in to replace the existing one, like the turbine. "It Should Just Work™" (and it does :smile:).

Screenshot:
![image](https://cloud.githubusercontent.com/assets/1733537/6056316/ed3e86ba-acdc-11e4-9a89-409389a95ee4.png)

Blender project files available if desired (I didn't include them in the mod because they're kinda big).

I should probably rename some of these textures, otherwise models will have weird images on their faces if a mesecons-aware texture pack that hasn't been adapted for these model is being used (they will still have the right shapes, however, and the user could just delete the offending images from their texture pack if necessary).

Use of mesh nodes will generate bogus warnings about missing .mtl files.  This is an engine bug, just ignore it, it's harmless.  These meshes depend on the basic support in the engine that was merged in the fourth week of October; users who have Minetest builds that are too old will see cubes where the meshes should be.

**Comment by MT-Modder** [comment]
Maybe this could be merged now?

**Comment by VanessaE** [comment]
The wall levers were really more of a "first draft" - I've just pushed a revised version to the meshes branch that looks better.  No changes to the water turbine.  Both should be suitable for merge after review.

**Comment by Jeija** [comment]
All right, I just merged the meshes branch into the master branch.
@VanessaE, you may also just push any meshes-related changes directly to the master branch (unless they like completely throw over what the nodes used to look like)

**Comment by MT-Modder** [comment]
Nice work @VanessaE. Thanks @Jeija, mesh nodes make minetest look way better..
