### ISSUE TITLE
Normal Chest and Protection

### ISSUE THREAD

**Issue by tenplus1** [Jeija/minetest-mod-mesecons#203]
Not so much an issue as a request to add default chest, and protection redo blocks to the end of the mesecons/mesecons_mvps/init.lua file :)

mesecon:register_mvps_stopper("default:chest")
mesecon:register_mvps_stopper("protector:protect")
mesecon:register_mvps_stopper("protector:protect2")

**Comment by cheapie** [comment]
I can understand the protector stuff, but why do you want the chest to stop it?

**Comment by MT-Modder** [comment]
@cheapie Metadata probably is the issue here.

**Comment by cheapie** [comment]
I've never had an issue moving full chests with pistons. In fact, as a server admin, I've occasionally had to use pistons to move nodes owned by other people that contained items.

**Comment by MT-Modder** [comment]
You're right. Maybe it also has to do with protection. Bookshelves should be added too if so.

**Comment by Jeija** [comment]
Merged @MT-Modder's changes in #216
I know there are advantages and disadvantages to this, so if lots of people prefer reverting to the behaviour before the merge, I'll be fine with it.

**Comment by HybridDog** [comment]
l liked the possibility to move chests.

**Comment by cheapie** [comment]
Hmm... maybe pistons/movestones should be able to move this stuff, but have ownership and obey protection?
