### ISSUE TITLE
door textures not found

### ISSUE THREAD

**Issue by MT-Modder** [Jeija/minetest-mod-mesecons#204]
Due to this commit: https://github.com/minetest/minetest_game/commit/61579827875f42a08797229895a2fc2ad8bc3355

**Comment by HybridDog** [comment]
Why does mesecons need the door textures?

**Comment by MT-Modder** [comment]
Compatibility for some reason :).
Look at the mesecons_compatibility mod for more info.

**Comment by HybridDog** [comment]
https://github.com/Jeija/minetest-mod-mesecons/blob/master/mesecons_compatibility/init.lua#L174
Why isn't minetest.registered_nodes["doors:door_wood"] used?

**Comment by MT-Modder** [comment]
Good point! I think you would still have to redefine the on_rightclick function. And you would have to use minetest.registered_nodes["doors:door_wood_b_1"] and minetest.registered_nodes["doors:door_wood_b_2"].

**Comment by HybridDog** [comment]
l think the doors mod should store input of doors.register_door(name, input) into a table called doors.registered_doors with name as index.

**Comment by MT-Modder** [comment]
Yeah that would be the easiest solution. I know pilzadam is going to write the doors mod so I'll suggest it to him.

**Comment by MT-Modder** [comment]
Unfortunately after two hours of testing, the way it's implemented now is the best way :frowning: If you can get it to work go for it but I've tried everything I can. The only way to fix the current issue is to add a "s" to the textures.

**Comment by MT-Modder** [comment]
I submitted a pull request for this issue. Here: https://github.com/Jeija/minetest-mod-mesecons/pull/207
