### ISSUE TITLE
(Enhancement) "Timer" events on LuaCs

### ISSUE THREAD

**Issue by cheapie** [Jeija/minetest-mod-mesecons#206]
An event that fires once per second (probably with an event.type of "timer") would be a nice alternative to hooking up blinky plants to LuaCs that need to do something repeatedly. This would break some programs that do something or other on an event and don't check the type, but writing programs like that is probably a bad idea anyway, and can be fixed by doing this:

if (event.type ~= "timer") then
--existing code here
end

**Comment by Jeija** [comment]
Something very similar already exists. Check out "Chapter IV: Interrupts" at http://mesecons.net/luacontroller/

**Comment by cheapie** [comment]
Yes, but interrupts are unreliable (they don't persist across server restarts, mainly).

**Comment by CiaranG** [comment]
They are reliable and persist across server restarts (since last March). See df6829e5538
