### ISSUE TITLE
Doors Texture Problems

### ISSUE THREAD

**Issue by C1ffisme** [Jeija/minetest-mod-mesecons#212]
With the latest dev version of minetest, the door textures are renamed so that the "doors" prefix is added. But, mesecons is still overriding the door mod and using a texture that isn't there. All this bug really needs done is some renaming, so this is an easy bug to fix. (In fact, why don't I just make a pull request?)

**Comment by Jeija** [comment]
You're propably not running the latest version of mesecons. This issue was fixed in 562cee7438ec43fd8e56eff3359326c54c7a6816, now mesecons uses whatever textures the door mod uses. Feel free to reopen this issue if the problem remains after updating mesecons.
