### ISSUE TITLE
mesecons_detector makes server crash

### ISSUE THREAD

**Issue by yo-we** [Jeija/minetest-mod-mesecons#228]
Today we got dozens of these in a row (causing server crash)

As the Hud caused a lot of trouble these days, we deactivated it. Thus we are sure that this time the Hud was not causing the crash. Pipeworks and technics are up to date.

The player did not use an electric tool (but had empty Laser and Drill in his inventory)
The server crashed on each reconnection of the player until his Spawn point was set far away from where he had been (mining). Presence of lava.

Not sure that this is really linked to the player, by the way, nevertheless it cost some 15 server crashes in roughly 3 minutes.

14:15:59: ACTION[main]: IRC: Disconnected.
14:16:00: ERROR[main]: ERROR: An unhandled exception occurred: ...opt/minetest-0.4.12/bin/../builtin/common/vector.lua:104: attempt to perform arithmetic on local 'b' (a nil value)
14:16:00: ERROR[main]: stack traceback:
14:16:00: ERROR[main]: 	...opt/minetest-0.4.12/bin/../builtin/common/vector.lua:104: in function 'subtract'
14:16:00: ERROR[main]: 	...e/minetest/.minetest/mods/mesecons_detector/init.lua:139: in function 'node_detector_scan'
14:16:00: ERROR[main]: 	...e/minetest/.minetest/mods/mesecons_detector/init.lua:251: in function <...e/minetest/.minetest/mods/mesecons_detector/init.lua:250>

**Comment by Jeija** [comment]
Please tell me if the commit fixed this issue, I just assumed that this crash is caused by some kind of unloaded area or otherwise invalid node data.

**Comment by yo-we** [comment]
Jeija, it did not appear again. Thank you.
