### ISSUE TITLE
No crafting recipe for NOR gate

### ISSUE THREAD

**Issue by cheapie** [Jeija/minetest-mod-mesecons#243]
No crafting recipe seems to be registered for the NOR gate. All of the other ones seem to be fine, so I have no idea what's going on here...

**Comment by Jeija** [comment]
Thanks for reporting, I forgot to upload my local changes to the nor gate, so the documentation didn't match the old recipe. [This](http://mesecons.net/minetest-mod-mesecons/mesecons_gates/doc/nor/recipe.png) recipe should work just fine now.

**Comment by HybridDog** [comment]
the recipe picture can take less space:
![recipe](https://cloud.githubusercontent.com/assets/3192173/11848660/ce667196-a423-11e5-89e8-e516a2e0d256.png)
