### ISSUE TITLE
os.date()

### ISSUE THREAD

**Issue by cheapie** [Jeija/minetest-mod-mesecons#246]
Is there a reason that the os.date function is not allowed in LuaCs? It seems like it should be fine, and it (or even a simple wrapper) would stop me from having to roll my own date-formatting code.

**Comment by Jeija** [comment]
According to http://lua-users.org/wiki/SandBoxes :
> os.date - UNSAFE - This can crash on some platforms (undocumented). For example, os.date'%v'. It is reported that this will be fixed in 5.2 or 5.1.3. 

And I really don't want to take any risks when it comes to executing untrusted code on servers.

**Comment by HybridDog** [comment]
If you make a wrapper, risks shouldn't appear.

**Comment by cheapie** [comment]
Even just a wrapper for it that does nothing but return a date table for the current date/time would be adequate for my (and likely most) use cases.

**Comment by Jeija** [comment]
Adding a wrapper the returns the date in a table sounds okay to me. We just shouldn't do that for all potentially unsafe calls to not unneccessarily bloat the luacontroller code. If you implement it, it would be great if you could also document it in [the luacontroller documentation](https://github.com/Jeija/mesecons.net/blob/master/luacontroller/index.html).

**Comment by cheapie** [comment]
A simple implementation of this has been done, and the following two PRs have been created.

https://github.com/Jeija/minetest-mod-mesecons/pull/247
https://github.com/Jeija/mesecons.net/pull/10

I'm closing this issue now since any further discussion should most likely be there.
