### ISSUE TITLE
Possible DoS with string.gsub and string.rep

### ISSUE THREAD

**Issue by pgimeno** [Jeija/minetest-mod-mesecons#255]
I've found the following DoS attacks related to the global `string` table (all found with LuaJIT, but I guess pure Lua is affected since these are C functions):

----

```lua
string.gsub(string.rep("a", 50), string.rep("a?", 50)..string.rep("a", 50),"x")
```
This is a variation of https://love2d.org/forums/viewtopic.php?t=80128 adapted to use `string.gsub` instead of `string.find` (since the latter isn't in the sandbox). Note that that thread is about sandboxing and might contain pertinent information.

Disallowing string.gsub is advisable for this reason.

----

```lua
string.rep("abcd",10000000)
string.rep("abcd",10000000)
string.rep("abcd",10000000)
string.rep("abcd",10000000)
string.rep("abcd",10000000)
string.rep("abcd",10000000)
string.rep("abcd",10000000)
--...
```
Each individual string.rep takes a long time to complete, so concatenating several of them results in a very long time overall. Redefining string.rep in the sandbox to block the call if `#str*reps` > (some threshold, say 64Kb) would be enough to fix it.

**Comment by Jeija** [comment]
Added a safe version of `string.rep` as you suggested (I think it is important enough to have string manipulation functions since luacontrollers may be used to drive displays and such). I don't think `string.gsub()` can be fixed that easily, so I removed it completely. Thanks for reporting!

**Comment by 12Me21** [comment]
Why not just have the same kind of length limit for `string.gsub`?

**Comment by pgimeno** [comment]
Because processing can be extremely slow even with relatively short strings. For example:

```lua
string.gsub('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 'a*a*a*a*a*a*a*b', 'x')
```

takes 4 seconds in my machine.

One possible solution would be to reimplement patterns in pure Lua, using the NFA approach instead of backtracking, but that's a complex task requiring someone willing to take on it. See https://swtch.com/~rsc/regexp/regexp1.html - but don't hold your breath.

**Comment by numberZero** [comment]
See #387. The C sandbox I’m working on is able to interrupt native code, including regexp processing.
