### ISSUE TITLE
Unable to craft sticky blocks.

### ISSUE THREAD

**Issue by WSDguy2014** [Jeija/minetest-mod-mesecons#258]
Hello, i'm trying to craft all sides of sticky block, requires 9 glues, but i can't. Only can be obtained by using creative mode or /giveme command.

In Minecraft version 1.8 and later, you can craft Slime Block (Sticky Block) by using 9 slimeballs, you can convert Slime Block into 9 slimeballs back.

**Comment by C1ffisme** [comment]
Sticky Blocks are still very experimental. I don't know if they have a crafting recipe yet.

**Comment by Jeija** [comment]
@C1ffisme That is correct. I honestly don't want to add a crafting recipe for them due to their experimental status and because they may not be included in mesecons in the long term (they're not even listed on mesecons.net).
I'm sorry, @WSDguy2014. If you really need people to have sticky blocks on a server (which I don't recommend since they're so experimental) you will have to provide your own recipe.

**Comment by C1ffisme** [comment]
This code should work:
```
minetest.register_craft({
    output = "mesecons_stickyblocks:sticky_block_all",
    recipe = {
        {"mesecons_materials:glue","mesecons_materials:glue","mesecons_materials:glue"},
        {"mesecons_materials:glue","mesecons_materials:glue","mesecons_materials:glue"},
        {"mesecons_materials:glue","mesecons_materials:glue","mesecons_materials:glue"}
    },
})
```

You might have to test it before you run it, though.

**Comment by WSDguy2014** [comment]
@C1ffisme, good, i added code, should work:

`minetest.register_craft({
    output = "mesecons_materials:glue 9",
    recipe = {
        {"mesecons_stickyblocks:sticky_block_all"},
    },
})`

You might have to test it before you run it, though.

**Comment by WSDguy2014** [comment]
@C1ffisme, good. I added code, but, i don't know, how to paste code?

**Comment by C1ffisme** [comment]
@WSDguy2014 Wait... So you added the code, but you don't know how to paste it???

Those two things seem to contradict each other. (How did you add the code if you didn't paste it, unless you copied it word for word?)

If you need some help, I would suggest reading up a bit on mods and their [structure](http://dev.minetest.net/Intro#Mod_folder_structure). It's not too hard to learn, and you can do it in the time frame of a few minutes.

**Comment by WSDguy2014** [comment]
@C1ffisme, im trying to paste this code, this happens:

`minetest.register_craft({`
`    output = "mesecons_materials:glue 9",`
`    recipe = {`
`        {"mesecons_stickyblocks:sticky_block_all"},`
`    },`
`})`

**Comment by C1ffisme** [comment]
@WSDguy2014 Ah... Yes... I forgot that I used spaces, since I can't type tabs in github.

I'm not sure where you got that code from, since I made the code to create sticky blocks, not destroy them.
