### ISSUE TITLE
Copyright and license

### ISSUE THREAD

**Issue by SnarkBoojum** [Jeija/minetest-mod-mesecons#268]
Hi,

I've almost finished packaging mesecons in Debian, and I'm checking the licenses on different files.
I know which license apply to most parts, namely:

    Files: *
    License: LGPL-3
    
    Files: */textures/*
    License: CC-BY-SA-3.0`
    
    Files: */sounds/*
    License: CC-BY-SA-3.0

but I lack copyright assignments... could you document them in LICENSE.txt? Even something like "Mesecons Team" is better than the triple question marks that I have for now.

Thanks!

**Comment by sofar** [comment]
That seems more of an artificial problem for Debian than a real one. You can find the submitter from the git log. Creating an artificial nonexistant legal name ("Mesecons Team") doesn't seem prudent either, since nobody can claim that they represent it.

**Comment by SnarkBoojum** [comment]
Git logs show who committed the file -- that may not be the same person as the author.

Git logs sometimes give what I think is a real name, like "Auke Kok" (but is it really one?), and sometimes a surname, like "Jeija" (but is it really one?).

It would be nice to document things more properly.

**Comment by sofar** [comment]
I'm not necessarily saying that it isn't nicer to do that.

What I'm saying that this is a self-imposed problem by Debian.

But hey, patches will always be considered seriously.

**Comment by Jeija** [comment]
I just added a COPYING.txt file (https://github.com/Jeija/minetest-mod-mesecons/commit/85bc62a65d05c6e6066fba12b6551364561ab207) that attributes copyright to the Mesecons Mod Developer Team. Does this work for you, @SnarkBoojum? If so, I will publish a new release that contains the COPYING.txt file.

And yes, your license assignments are basically correct. However, documentation files are also licensed under the CC-BY-SA license (LGPL just doesn't make a lot of sense there), so it should be
```
Files: *
License: LGPL-3

Files: */textures/*
License: CC-BY-SA-3.0`

Files: */sounds/*
License: CC-BY-SA-3.0

Files: */doc/*/*
License: CC-BY-SA-3.0
```

Thank you very much for your effort again!

**Comment by SnarkBoojum** [comment]
No need for a new release just for that : as long as the information is available in git and in future releases, that's perfect.

Perhaps I won't be the one to do the packaging after all, but it should still be packaged quite soon.

Thanks!
