### ISSUE TITLE
Player Detector with NOT-Gate/LUA Controller don't work

### ISSUE THREAD

**Issue by darkfeels** [Jeija/minetest-mod-mesecons#278]
Hy,

I've bulid on a server and on my local PC different combinations with the Player Detector in Combination with a NOT-Gate oder a LUA Controller. I think, since the last Update of Mesecons, all of my Mesecons Buldings does not function correctly.
So I'd tested out and find out, that the Problem comes from the Gate or from the LUA Controller.
Example: 
Player Detector -> NOT Gate -> Pistons
So long I will be in the near of the Player Detector (it is green) the Piston is closed (not extendet) but I've I go away, so that the state of the detector will change, the piston goes very fast in/out/in/out/in/out..... And after some seconds my NOT gate will break down.
The same happens, when the Detector is red, the detector will change the state and it goes in/out/in/out/out....

Nearly the same Problem will happen when I use the LUA Controller.
Player Detector -> LUA Controller -> Piston
LUA Controller:
`if pin.b then
port.d=false
else
port.d=true
end`

The Player Detector works, but when the Cotroller should change the state of port.d it dosen't work. The Port.d is always on nevemind if pin.b is on or off.

I've build everything new and cloned the latest mesecons version and use the latest stable 0.4.14 Windows Version. But it don't helps :(

Hopefully the bug will be fixed :)

**Comment by Jeija** [comment]
Confirming, something has gone horribly wrong with the last commit. Currently investigating...

**Comment by Jeija** [comment]
Thanks for reporting, I can't believe I didn't notice this bug while testing (I guess it's because I didn't think my latest change needed heavy testing, since it should have only affected forceloading) . I've pushed a commit that should fix this. Please test this again with the new commit!

**Comment by darkfeels** [comment]
Wow thats was very fast. And I thought you need some time to fix :)
And the great thing is that it works :) 
Thank You :+1:
