### ISSUE TITLE
Nodes can be placed inside water turbine, causes horrible Z-fighting

### ISSUE THREAD

**Issue by Wuzzy2** [Jeija/minetest-mod-mesecons#293]
You can place any node directly in the top part of the water turbine (the turbine itself) by placing the node from above (i.e. on top of the turbine). If you placed a full node e.g. dirt, this will cause a horribly-looking Z-fighting.

**Comment by DS-Minetest** [comment]
So, move the top part of the mesh a bit down?

**Comment by sofar** [comment]
Yes, that's a method that works reasonably well in most cases.

**Comment by VanessaE** [comment]
That would work, though it doesn't address the problem of being able to place a node in that upper space to begin with.  I'll submit a revision to the model soon to address the Z-fighting.

**Comment by VanessaE** [comment]
fa3bd1927042ca5ded14623226f447bcb907b953
