### ISSUE TITLE
Deployers do not use blocks

### ISSUE THREAD

**Issue by emuNAND** [Jeija/minetest-mod-mesecons#296]
When using a deployer with one block inside, it will place the block **and** keep it inside of the delpoyer. This can be used as a way to duplicate objects, which is bad.

**Comment by Jeija** [comment]
Are you talking about the deployer in the [technic mod](https://github.com/minetest-technic/technic)? If so, please report the issue on their bug tracker and close this issue, this is not a mesecons problem. Or am I misunderstanding?

**Comment by emuNAND** [comment]
oops, this was supposed to be on the pipeworks mod. sorry

**Comment by Jeija** [comment]
Oh wow, then we both mixed up mods 😄
