### ISSUE TITLE
Buttons and wall levers can be rotated around axis, which causes weirdness

### ISSUE THREAD

**Issue by Wuzzy2** [Jeija/minetest-mod-mesecons#298]
You can use the screwdriver from Minetest Game to rotate the buttons and wall levers around their axis.

I think it is OK to horizontally rotate these things as the mod still works just fine. But if you start rotating these things around their axis, and then push the button or use the lever, odd things happen. The signal does not go where I expect it to go.
I think it would be best to disallow axis rotation (see Minetest Game API).

**Comment by cheapie** [comment]
The PR I just referenced this in (#304, see above) would fix this by still allowing them to be axis rotated, and fixing the param2 parsing such that the signals do properly follow the orientation of the button/lever. It also allows the "receivers" to connect properly to a floor/ceiling-mounted button or lever.

**Comment by Jeija** [comment]
This is now taken care of in 1bd936ad8c9e326f9466af66d78c8bda75bfd1c6. Thanks for the bug report.
