### ISSUE TITLE
Question about the button

### ISSUE THREAD

**Issue by paly2** [Jeija/minetest-mod-mesecons#328]
Hello,
I'm wondering why this code, executed in an external mod depending on both mesecons and mesecons_button, doesn't work:
```lua
-- `pos` is the position of the button
local node = minetest.get_node(pos)
minetest.swap_node(pos, {name = "mesecons_button:button_on", param2=node.param2})
mesecon.receptor_on(pos, mesecon.rules.buttonlike_get(node))
minetest.sound_play("mesecons_button_push", {pos=pos})
minetest.after(1, mesecon.button_turnoff, pos)
```
The button swaps and the sound is played, but no signal is emitted...

I also tried the following, but it does the same:
```lua
minetest.registered_items["mesecons_button:button_off"].on_rightclick(pos, minetest.get_node(pos))
```

**Comment by Jeija** [comment]
I don't spot anything obvious here - have you made sure the button works just fine when manually pressed by a player? Maybe you could try to find out why this doesn't work by adding some debug output to `receptor_on`, the `receptor_on` actionqueue function (both in `mesecons/init.lua`) and `mesecon.turnon` (in `mesecons/internal.lua`).

**Comment by paly2** [comment]
Thanks, by adding debug output to these functions, I found out that my `pos` had many decimals - a `vector.round` sorted out that problem 😃 
Maybe I would be good to add that `vector.round` in the `mesecon.*` functions (just like in minetest API functions)?
